In [1]:
import numpy as np
import scipy
np.set_printoptions(precision=3)

In [5]:
ndata = 1000
xdims = 2
ydims = 2
tdims = xdims + ydims

A = np.random.rand(tdims, tdims)
#cov = A.dot(A.T)
XY = np.random.standard_normal(size=(ndata, xdims+ydims))
XY = XY - XY.mean(axis=0)
XY = XY.dot(A.T)
X = XY[:, :xdims]
Y = XY[:, xdims:]

covXY = np.cov(XY.T)
covX = covXY[:xdims,:xdims]
covY = covXY[xdims:,xdims:]

covXgY = covX - covXY[:xdims,xdims:].dot(np.linalg.inv(covY)).dot(covXY[xdims:,:xdims])

#http://www.jmlr.org/papers/volume6/chechik05a/chechik05a.pdf
mainMx = covXgY.dot(np.linalg.inv(covX))

evecs, evals = np.linalg.eig(mainMx)
assert(np.all(evecs >= 0) and np.all(evecs <= 1))

print(evecs)

[0.007 0.831]


In [91]:
ndata = 1000
xdims = 2
ydims = 2
tdims = xdims + ydims

A = np.random.rand(tdims, tdims)
cov = A.dot(A.T)
#print(cov)
XY = np.random.standard_normal(size=(ndata, xdims+ydims))
XY = XY - XY.mean(axis=0)
XY = XY.dot(A.T)
X = XY[:, :xdims]
Y = XY[:, xdims:]

covX = np.cov(X.T)
covY = np.cov(Y.T)

covXY = np.cov(XY.T)
covX = covXY[:xdims,:xdims]
covY = covXY[xdims:,xdims:]

covYgX = covY - covXY[xdims:,:xdims].dot(np.linalg.inv(covX)).dot(covXY[:xdims,xdims:])
covYgX2 = covY - covXY[:xdims,xdims:].dot(np.linalg.inv(covX)).dot(covXY[xdims:,:xdims])

covXgY = covX - covXY[xdims:,:xdims].dot(np.linalg.inv(covY)).dot(covXY[:xdims,xdims:])
covXgY2 = covX - covXY[:xdims,xdims:].dot(np.linalg.inv(covY)).dot(covXY[xdims:,:xdims])

#http://www.jmlr.org/papers/volume6/chechik05a/chechik05a.pdf
mx2 = covXgY.dot(np.linalg.inv(covX))
mx2b = covXgY2.dot(np.linalg.inv(covX))

#print(XY.mean(axis=0))
#print(np.cov(XY.T))
#print(cov)

# https://stats.stackexchange.com/questions/186402/expressing-conditional-covariance-matrix-in-terms-of-covariance-matrix
#cov = np.cov(XY)

In [92]:
print(np.linalg.eig(mx2))
evecs, evals = np.linalg.eig(mx2b)[0]
assert(np.all(evecs >= 0) and np.all(evecs <= 1))



(array([ 0.998, -9.039]), array([[0.972, 0.353],
       [0.234, 0.936]]))
(array([0.102, 0.982]), array([[-0.82 ,  0.612],
       [-0.572, -0.791]]))


In [70]:
covYgX2

array([[ -8.019, -14.958],
       [-14.958, -25.523]])

In [61]:
covXY

array([[1.696, 0.519, 1.258, 1.739],
       [0.519, 0.393, 0.718, 0.853],
       [1.258, 0.718, 1.433, 1.728],
       [1.739, 0.853, 1.728, 2.401]])

In [62]:
XY.shape

(1000, 4)

In [63]:
covY

array([[1.433, 1.728],
       [1.728, 2.401]])